version: '3'

networks:
  scrapper-network:
    driver: bridge

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - scrapper-network
    logging:
        driver: none
    command: mongod --quiet --logpath /dev/null 

  web:
    container_name: web
    build:
      context: ./web
      tags:
        - "scrapper-web"
    ports:
      - 3000:3000
    depends_on:
      - mongo
      - api
    networks:
      - scrapper-network
    logging:
        driver: none

  api:
    container_name: api
    build:
      context: ./api
      tags:
        - "scrapper-api"
    restart: always
    ports:
      - 3001:3001
      - 8080:8080
    environment:
      NODE_ENV: development
      PORT: 3001
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_USER: user
      MONGODB_PASSWORD: password
    networks:
      - scrapper-network
